// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickDelivery.Database;

#nullable disable

namespace QuickDelivery.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250616220624_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductCategories", b =>
                {
                    b.Property<int>("CategoriesCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsProductId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesCategoryId", "ProductsProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instructions")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            City = "Bucuresti",
                            Country = "Romania",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefault = true,
                            PostalCode = "100001",
                            Street = "Strada Principala 1",
                            UserId = 1
                        },
                        new
                        {
                            AddressId = 2,
                            City = "Bucuresti",
                            Country = "Romania",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefault = true,
                            PostalCode = "100002",
                            Street = "Strada Restaurantului 5",
                            UserId = 2
                        },
                        new
                        {
                            AddressId = 3,
                            City = "Bucuresti",
                            Country = "Romania",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Instructions = "Apartament 4, et. 2",
                            IsDefault = true,
                            PostalCode = "100003",
                            Street = "Bulevardul Unirii 15",
                            UserId = 3
                        },
                        new
                        {
                            AddressId = 4,
                            City = "Bucuresti",
                            Country = "Romania",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Instructions = "Birou, et. 3",
                            IsDefault = false,
                            PostalCode = "100004",
                            Street = "Strada Victoriei 25",
                            UserId = 3
                        },
                        new
                        {
                            AddressId = 5,
                            City = "Bucuresti",
                            Country = "Romania",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Instructions = "Bloc A, scara 1, apt. 15",
                            IsDefault = true,
                            PostalCode = "100005",
                            Street = "Calea Floreasca 100",
                            UserId = 4
                        },
                        new
                        {
                            AddressId = 6,
                            City = "Bucuresti",
                            Country = "Romania",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefault = true,
                            PostalCode = "100006",
                            Street = "Strada Aviatorilor 8",
                            UserId = 5
                        },
                        new
                        {
                            AddressId = 7,
                            City = "Bucuresti",
                            Country = "Romania",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Instructions = "Vila, poarta alba",
                            IsDefault = true,
                            PostalCode = "100007",
                            Street = "Bulevardul Herastrau 45",
                            UserId = 10
                        },
                        new
                        {
                            AddressId = 8,
                            City = "Bucuresti",
                            Country = "Romania",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefault = true,
                            PostalCode = "100008",
                            Street = "Strada Pizzeriei 12",
                            UserId = 9
                        });
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quick meals and snacks",
                            IsActive = true,
                            Name = "Fast Food"
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Various pizza types",
                            IsActive = true,
                            Name = "Pizza"
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Asian cuisine",
                            IsActive = true,
                            Name = "Asian Food"
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sweet treats",
                            IsActive = true,
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Bulevardul Unirii 15",
                            City = "Bucuresti",
                            Country = "Romania",
                            Name = "John Doe",
                            PostalCode = "100003",
                            UserId = 3
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Calea Floreasca 100",
                            City = "Bucuresti",
                            Country = "Romania",
                            Name = "Jane Smith",
                            PostalCode = "100005",
                            UserId = 4
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Bulevardul Herastrau 45",
                            City = "Bucuresti",
                            Country = "Romania",
                            Name = "Maria Rodriguez",
                            PostalCode = "100007",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryId"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrentLatitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("CurrentLongitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DelivererId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DelivererRating")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("DelivererReview")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeliveryNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastLocationUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("DeliveryId");

                    b.HasIndex("DelivererId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("ActualDeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryAddressId")
                        .HasColumnType("int");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("EstimatedDeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int?>("PickupAddressId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("PartnerId");

                    b.HasIndex("PickupAddressId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartnerId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PartnerId");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            PartnerId = 1,
                            AddressId = 2,
                            AverageRating = 4.5m,
                            BusinessName = "Delicious Restaurant",
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Best food in town",
                            IsActive = true,
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0),
                            TotalOrders = 0,
                            UserId = 2
                        },
                        new
                        {
                            PartnerId = 2,
                            AddressId = 8,
                            AverageRating = 4.8m,
                            BusinessName = "Mario's Pizza Palace",
                            CloseTime = new TimeSpan(0, 23, 0, 0, 0),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentic Italian pizza made with love",
                            IsActive = true,
                            LogoUrl = "https://example.com/mario-logo.png",
                            OpenTime = new TimeSpan(0, 10, 0, 0, 0),
                            TotalOrders = 0,
                            UserId = 9,
                            Website = "https://mariospizza.com"
                        });
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentGateway")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.HasIndex("PartnerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Pizza",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic pizza with tomato sauce, mozzarella and basil",
                            IsAvailable = true,
                            Name = "Margherita Pizza",
                            PartnerId = 1,
                            Price = 25.50m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Fast Food",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Juicy beef burger with cheese",
                            IsAvailable = true,
                            Name = "Cheeseburger",
                            PartnerId = 1,
                            Price = 18.00m,
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Asian Food",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Traditional Thai noodles with chicken",
                            IsAvailable = true,
                            Name = "Chicken Pad Thai",
                            PartnerId = 1,
                            Price = 22.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Desserts",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rich chocolate cake with cream",
                            IsAvailable = true,
                            Name = "Chocolate Cake",
                            PartnerId = 1,
                            Price = 15.00m,
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Pizza",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic pepperoni pizza with mozzarella",
                            IsAvailable = true,
                            Name = "Pepperoni Pizza",
                            PartnerId = 2,
                            Price = 28.00m,
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 6,
                            Category = "Pizza",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Four seasons pizza with ham, mushrooms, olives and artichokes",
                            IsAvailable = true,
                            Name = "Quattro Stagioni",
                            PartnerId = 2,
                            Price = 32.00m,
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 7,
                            Category = "Desserts",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Traditional Italian dessert with coffee and mascarpone",
                            IsAvailable = true,
                            Name = "Tiramisu",
                            PartnerId = 2,
                            Price = 18.00m,
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductId = 8,
                            Category = "Fast Food",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crispy bread with garlic butter and herbs",
                            IsAvailable = true,
                            Name = "Garlic Bread",
                            PartnerId = 2,
                            Price = 12.00m,
                            StockQuantity = 60
                        });
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@quickdelivery.com",
                            FirstName = "Admin",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "QuickDelivery",
                            PasswordHash = "$2a$11$bfPciUVybJ3vtJOW.5JvQu6sYqgf1wu76PbwsIlYByyzVTZ6KsJkO",
                            PhoneNumber = "+40123456789",
                            Role = 4,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "partner@restaurant.com",
                            FirstName = "Restaurant",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Owner",
                            PasswordHash = "$2a$11$bfPciUVybJ3vtJOW.5JvQu6sYqgf1wu76PbwsIlYByyzVTZ6KsJkO",
                            PhoneNumber = "+40123456790",
                            Role = 3,
                            Username = "restaurant_owner"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john.doe@email.com",
                            FirstName = "John",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$bfPciUVybJ3vtJOW.5JvQu6sYqgf1wu76PbwsIlYByyzVTZ6KsJkO",
                            PhoneNumber = "+40123456791",
                            Role = 1,
                            Username = "john_doe"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane.smith@email.com",
                            FirstName = "Jane",
                            IsActive = true,
                            IsEmailVerified = false,
                            LastName = "Smith",
                            PasswordHash = "$2a$11$bfPciUVybJ3vtJOW.5JvQu6sYqgf1wu76PbwsIlYByyzVTZ6KsJkO",
                            PhoneNumber = "+40123456792",
                            Role = 1,
                            Username = "jane_smith"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mike.deliverer@email.com",
                            FirstName = "Mike",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$bfPciUVybJ3vtJOW.5JvQu6sYqgf1wu76PbwsIlYByyzVTZ6KsJkO",
                            PhoneNumber = "+40123456793",
                            Role = 2,
                            Username = "mike_deliverer"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sarah.deliverer@email.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Wilson",
                            PasswordHash = "$2a$11$bfPciUVybJ3vtJOW.5JvQu6sYqgf1wu76PbwsIlYByyzVTZ6KsJkO",
                            PhoneNumber = "+40123456794",
                            Role = 2,
                            Username = "sarah_deliverer"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@quickdelivery.com",
                            FirstName = "David",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Manager",
                            PasswordHash = "$2a$11$bfPciUVybJ3vtJOW.5JvQu6sYqgf1wu76PbwsIlYByyzVTZ6KsJkO",
                            PhoneNumber = "+40123456795",
                            Role = 5,
                            Username = "david_manager"
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "inactive@email.com",
                            FirstName = "Inactive",
                            IsActive = false,
                            IsEmailVerified = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$bfPciUVybJ3vtJOW.5JvQu6sYqgf1wu76PbwsIlYByyzVTZ6KsJkO",
                            PhoneNumber = "+40123456796",
                            Role = 1,
                            Username = "inactive_user"
                        },
                        new
                        {
                            UserId = 9,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pizza.owner@restaurant.com",
                            FirstName = "Pizza",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Owner",
                            PasswordHash = "$2a$11$bfPciUVybJ3vtJOW.5JvQu6sYqgf1wu76PbwsIlYByyzVTZ6KsJkO",
                            PhoneNumber = "+40123456797",
                            Role = 3,
                            Username = "pizza_owner"
                        },
                        new
                        {
                            UserId = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria.vip@email.com",
                            FirstName = "Maria",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastLoginAt = new DateTime(2025, 6, 15, 22, 6, 23, 447, DateTimeKind.Utc).AddTicks(3219),
                            LastName = "Rodriguez",
                            PasswordHash = "$2a$11$bfPciUVybJ3vtJOW.5JvQu6sYqgf1wu76PbwsIlYByyzVTZ6KsJkO",
                            PhoneNumber = "+40123456798",
                            Role = 1,
                            Username = "maria_vip"
                        });
                });

            modelBuilder.Entity("ProductCategories", b =>
                {
                    b.HasOne("QuickDelivery.Core.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuickDelivery.Core.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Address", b =>
                {
                    b.HasOne("QuickDelivery.Core.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Customer", b =>
                {
                    b.HasOne("QuickDelivery.Core.Entities.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("QuickDelivery.Core.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Delivery", b =>
                {
                    b.HasOne("QuickDelivery.Core.Entities.User", "Deliverer")
                        .WithMany("DeliveriesAsDeliverer")
                        .HasForeignKey("DelivererId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuickDelivery.Core.Entities.Order", "Order")
                        .WithOne("Delivery")
                        .HasForeignKey("QuickDelivery.Core.Entities.Delivery", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deliverer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Order", b =>
                {
                    b.HasOne("QuickDelivery.Core.Entities.User", "Customer")
                        .WithMany("OrdersAsCustomer")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickDelivery.Core.Entities.Address", "DeliveryAddress")
                        .WithMany()
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickDelivery.Core.Entities.Partner", "Partner")
                        .WithMany("Orders")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuickDelivery.Core.Entities.Address", "PickupAddress")
                        .WithMany()
                        .HasForeignKey("PickupAddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("DeliveryAddress");

                    b.Navigation("Partner");

                    b.Navigation("PickupAddress");
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("QuickDelivery.Core.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuickDelivery.Core.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Partner", b =>
                {
                    b.HasOne("QuickDelivery.Core.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickDelivery.Core.Entities.User", "User")
                        .WithOne("Partner")
                        .HasForeignKey("QuickDelivery.Core.Entities.Partner", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Payment", b =>
                {
                    b.HasOne("QuickDelivery.Core.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("QuickDelivery.Core.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Product", b =>
                {
                    b.HasOne("QuickDelivery.Core.Entities.Partner", "Partner")
                        .WithMany("Products")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Order", b =>
                {
                    b.Navigation("Delivery");

                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Partner", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("QuickDelivery.Core.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Customer");

                    b.Navigation("DeliveriesAsDeliverer");

                    b.Navigation("OrdersAsCustomer");

                    b.Navigation("Partner");
                });
#pragma warning restore 612, 618
        }
    }
}
